name: Pylint

on:
- push
- pull_request

jobs:
  lint-ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      name: Set up Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Analysing the code with ruff
      run: |
        pip install -r test-requirements.txt
        ruff format --check
